const FETCH_GAMES = 'FETCH_GAMES'
const FETCH_PUBLISHERS = 'FETCH_PUBLISHERS'
const FETCH_GAMES_ENDED = 'FETCH_GAMES_ENDED'
const FETCH_PUBLISHERS_ENDED = 'FETCH_PUBLISHERS_ENDED'

export {
  FETCH_GAMES,
  FETCH_PUBLISHERS,
  FETCH_GAMES_ENDED,
  FETCH_PUBLISHERS_ENDED,
}
